### ISSUE TITLE
why the heck it has microphone???

### ISSUE THREAD

**Issue by ramrattle** [dekuNukem/Amazon_Dash_Button#1]
any idea why it has microphone, I thought its just a button.

**Comment by dekuNukem** [comment]
On iPhone it uses the microphone for the initial set-up. The phone would play ultrasound encoded with data, and microphone on the dash button hears it, decodes it and set up the network.

**Comment by ramrattle** [comment]
uh!!! thats one ugly way for pairing!! thanks for the reply..awesome write up.
