### ISSUE TITLE
Debug output

### ISSUE THREAD

**Issue by battlecow** [dekuNukem/Amazon_Dash_Button#2]
I have fenced in the Dash with DNS redirection as described: http://blog.nemik.net/2015/08/dash-button-corral/ but cannot get the device past the initial TLS handshake.  How do you connect to the device and get the debug output you posted?

**Comment by dekuNukem** [comment]
Sorry I'm focusing on documenting the hardware part of the Dash Button, and I don't have a lot of experience with the network stuff. Maybe try contacting the original author?

**Comment by battlecow** [comment]
I guess the first part of the issue is superfluous, I was mainly wondering how to connect to the hardware and get the debug output, that would be helpful in my own troubleshooting.

**Comment by dekuNukem** [comment]
Sorry, missed the second half...

To get the debug output use a USB to serial board like this one https://www.sparkfun.com/products/9873 , then look at the pinout pdf in the repository, PC6 is Debug TX, PC7 is Debug RX. Connect dash button's TX to USB serial bridge's RX to receive the debug output. Speed is 115200bps 8n1.

**Comment by battlecow** [comment]
Thanks!
