### ISSUE TITLE
Firmware dump

### ISSUE THREAD

**Issue by WonBeom** [dekuNukem/Amazon_Dash_Button#4]
I tried to read out from the chip by using your method.
But i got the file only 128kb.
In my head this is from ram. 
How can i read from flash memory?

**Comment by dekuNukem** [comment]
I used ST-Link Utility to dump the firmware, what I did was set the starting address to 0x0 and size to 0x100000 (1MB) like this: http://i.imgur.com/ug2mPDU.png , then save it to computer. The button still worked after I erased its flash and reflashed it so I think it's the correct way to dump the firmware.
