### ISSUE TITLE
Pin Connections

### ISSUE THREAD

**Issue by battlecow** [dekuNukem/Amazon_Dash_Button#5]
I have 2 buttons that I tore apart and soldiered up and connected to a ST-Link v2 USB ( http://www.amazon.com/ST-Link-V2-Emulator-Downloader-Programming/dp/B00RYVLN4U ) with the SWD IO and CLK points but have been unable to get them to be recognized by the device.  I have tried both Linux VM and a Windows box to no avail.  I have soldiered them a few times just in case the connection was poor.  They power up and when I attempt a connection from the ST-Link program I can see the LED change its power output slightly, but it is never able to discover the device.

What settings did you use with the ST-Link utility to connect?  Do you have any other ideas on what to check and troubleshoot?

Thanks!

**Comment by bjorn-p** [comment]
Hi, I have exactly the same problem. Did you find a solution ?
I suspect that the button downloaded a new firmware after connecting to my WiFi and that this update contains some kind of protection against using the ST-Link adapter.

**Comment by battlecow** [comment]
I wasn't ever able to get them working unfortunately.

**Comment by bjorn-p** [comment]
Ok then it is probably no longer usable. Thanks anyway for your answer.

**Comment by battlecow** [comment]
I ordered up 2 more since they are $.99 on Amazon right now, ill respond back here if i can get it working.

**Comment by bjorn-p** [comment]
That sounds great. It will probably work if you open them right away without a connection to your WiFi.

**Comment by Spacefish** [comment]
Maybe you got REV2 aswell, which don´t contain a ST Processor, but a Atmel SAM G55J?

**Comment by Spacefish** [comment]
Maybe you got REV2 aswell, which don´t contain a ST Processor, but a Atmel SAM G55J?

**Comment by Spacefish** [comment]
Maybe you got REV2 aswell, which don´t contain a ST Processor, but a Atmel SAM G55J?
